---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperon-studio
  namespace: hyperon
  labels:
    app: hyperon-studio
    version: 2.2.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperon-studio
  template:
    metadata:
      labels:
        app: hyperon-studio
        version: 2.2.3
    spec:
      containers:
        - name: hyperon-studio
          image: hyperonio/studio-postgresql:2.2.3
          imagePullPolicy: Always
          securityContext:
            privileged: false
          env:
            - name: HYPERON_DATABASE_URL
              value: jdbc:postgresql://postgres-postgresql.hyperon.svc.cluster.local:5432/hyperon
            - name: HYPERON_DATABASE_USERNAME
              value: postgres
            - name: HYPERON_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql
                  key: postgres-password
            - name: HYPERON_DATABASE_DIALECT
              value: postgresql
            - name: HYPERON_ENVIRONMENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /hyperon/actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /hyperon/actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: hyperon-studio
  namespace: hyperon
  labels:
    app: hyperon-studio
    version: 2.2.3
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hyperon-studio

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyperon-studio
  namespace: hyperon
  labels:
    app: hyperon-studio
    version: 2.2.3
  annotations:
    nginx.ingress.kubernetes.io/app-root: "/hyperon/app"
spec:
  rules:
    - host: hyperon.stacja.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hyperon-studio
                port:
                  number: 8080
