apiVersion: v1
kind: Namespace
metadata:
  name: stacja-it-httpd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: stacja-it-httpd
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.57
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: stacja-it-httpd
  labels:
    app: httpd
spec:
  ports:
  - port: 80
  selector:
    app: httpd

# kubectl apply -f 7.yaml
# kubectl get services -n stacja-it-httpd
# kubectl describe service httpd -n stacja-it-httpd
# kubectl port-forward svc/httpd -n stacja-it-httpd 8080:80
# http://localhost:8080/